name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.0
          version: 1

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 4.0.0
          php_version: 7.0
          configuration: phpunit.xml
          memory_limit: 256M